testSancrisoft/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace testSancrisoft.Models
{
    public class Applicant
    {
        [Key]
        public int idApplicant { get; set; }

        [Display(Name="Name")]
        public string name { get; set; }
        [Display(Name = "Last name")]
        public string lastName { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Telephone")]
        public string telephone { get; set; }
        [Display(Name = "Birth date")]
        public DateTime birthdate { get; set; }
        [Display(Name = "Biography")]
        public string biography { get; set; }
        [Display(Name = "Street address")]
        public string streetAddress { get; set; }
        [Display(Name = "City")]
        public string city { get; set; }
        [Display(Name = "Country")]
        public string country { get; set; }
        [Display(Name = "Postal code")]
        public string postalCode { get; set; }
        [Display(Name = "Photo")]
        public string photo { get; set; }


        public int idAppointment { get; set; }

        public virtual Appointment Appointment { get; set; }


        public virtual ICollection<ApplicantAttachment> ApplicantAttachment { get; set; }




    }
}

testSancrisoft/Models/ApplicantAttachment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace testSancrisoft.Models
{
    public class ApplicantAttachment
    {
        [Key]
        public int idApplicantAttachment { get; set; }

        public int idApplicant { get; set; }
        public virtual Applicant Applicant { get; set; }
        public string attachment { get; set; }
        public string description { get; set; }

      
    }
}

testSancrisoft/Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace testSancrisoft.Models
{
    public class Appointment
    {
        [Key]
        public int idAppointment { get; set; }

        public string Description { get; set; }

        public virtual ICollection<Applicant> Applicant { get; set; }

    }
}

testSancrisoft/Controllers/ApplicantsController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using testSancrisoft.DataAccess;
using testSancrisoft.Logic;
using testSancrisoft.Models;
using testSancrisoft.ViewModel;

namespace testSancrisoft.Controllers
{
    public class ApplicantsController : Controller
    {
        private ModelContext db = new ModelContext();

        // GET: Applicants
        public ActionResult Index()
        {
            var applicants = db.Applicants.Include(a => a.Appointment);              

            return View(applicants.ToList());
            
        }

        // GET: Applicants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return Redirect("/404.html");
            }
            var applicant = ApplicantLogic.FindById(id); 
            if (applicant == null)
            {
                return Redirect("/404.html");
            }

       
            return View(applicant);
        }

        // GET: Applicants/Create
        public ActionResult Create()
        {
            ViewBag.idAppointment = new SelectList(db.Appointments, "idAppointment", "Description");
            return View();
        }

        // POST: Applicants/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( ApplicantViewModel view)
        {
            if (ModelState.IsValid)
            {
                if (view.photoC!=null &&( view.photoC.ContentLength >= 1000000 || !view.photoC.ContentType.Contains("image")))
                {
                    ViewBag.idAppointment = new SelectList(AppointmentLogic.GetAppointment(), "idAppointment", "Description", view.idAppointment);
                    ModelState.AddModelError(string.Empty, "photo fiel can not weigh more than 1 bm and it must be a photo");
                    return View(view);
                }
                string ext = ".pdf,.docx,.doc";
                foreach (var item in view.files)
                {

                     if ( item!=null && (item.ContentLength>= 5000000|| (!ext.Contains( Path.GetExtension(item.FileName))
                        && !item.ContentType.Contains("image"))  ))
                    {
                        ViewBag.idAppointment = new SelectList(AppointmentLogic.GetAppointment(), "idAppointment", "Description", view.idAppointment);
                        ModelState.AddModelError(string.Empty, "attachments can not weigh more than 5 bm");
                        return View(view);
                    }
                    
                }
                var folder = "/Content/photos";
                var id=ApplicantLogic.SaveApplicant(view, Server.MapPath(folder));
                ContentEmail contentEmailApplicant = new ContentEmail {
                    message = string.Format(Configuration.messageApplicant, view.name, view.lastName),
                   subject=Configuration.subjectApplicant,
                   to=view.email
                };

                ContentEmail contentEmailAdmin = new ContentEmail
                {
                    message = string.Format( Configuration.messageAdmin, view.name, view.lastName,db.Appointments.Find( view.idAppointment).Description, id, HttpContext.Request.Url.AbsoluteUri),
                    subject = Configuration.subjectAdmin,
                    to = Configuration.emailAdmin
                };



                 ApplicantLogic.SendMail(contentEmailApplicant);
                 ApplicantLogic.SendMail(contentEmailAdmin);
                ViewBag.idAppointment = new SelectList(AppointmentLogic.GetAppointment(), "idAppointment", "Description", view.idAppointment);
                ViewBag.message = "Thank you for applying.Please check your email.";

                return View(new ApplicantViewModel());
            }

            ViewBag.idAppointment = new SelectList(AppointmentLogic.GetAppointment() , "idAppointment", "Description", view.idAppointment);
            return View(view);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

testSancrisoft/Views/Applicants/Create.cshtml
@model testSancrisoft.ViewModel.ApplicantViewModel

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm("Create", "Applicants", FormMethod.Post, new { enctype = "multipart/form-data" ,@id="registration"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Work with us</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birthdate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.birthdate, "", new { @class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.biography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.biography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.biography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.streetAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.streetAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.streetAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.postalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.postalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.postalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photoC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            
                    @Html.TextBoxFor(modelo => modelo.photoC, new { @type = "file",@class= "form-control", @accept = "image/*"  })
          
               
            </div>
        </div>
        <div class="form-group" id="files">
            @Html.LabelFor(model => model.files, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              
                    @Html.TextBoxFor(modelo => modelo.files, new { @class= "col-md-6 form-control file", @type = "file" , @accept = "application/pdf,image/*,.doc,.docx" })
                <input type="text" class="col-md-6 form-control" name="descripciones" placeholder="Description file" value="" />
               
                <button id="addMore" style="margin-left:10px;" type="button" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-plus"></span> add more files
                </button>    
            </div>
       
           
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idAppointment, "idAppointment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idAppointment", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idAppointment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="guardar" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div id="map"></div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACJapLIVhm-uVWitwICh24232jYdkP1SQ&callback=initMap">
</script>

    <script src="~/Scripts/apiGoogle.js"></script>
<script src="~/Scripts/ApplicantJs.js"></script>
@{if (ViewBag.message != null && ViewBag.message != "")
    {
        <script type="text/javascript">
            $(".form-horizontal input, textarea").each(function () {
                if ($(this)[0].id != "guardar") {
                    $(this).val('');
                }
               
            });
            alert('@ViewBag.message');
        </script>
    }
}

  <script type="text/javascript">

      $(document).ready(function () {
          // validate the comment form when it is submitted
       


          $('#guardar').click(function (e) {
              var val = true;
              $.each($("[data-val='true']"), function (key, value) {


                  if (value.value === "") {
                      $(value).css("border", "1px solid red");
                      val = false;
                  }
              });
              if (val) {
                  $('#registration').submit();
              } else alert("Fields in red are required");

          });
      });



    </script>

}

testSancrisoft/Views/Applicants/Details.cshtml
@model testSancrisoft.ViewModel.AplicanDetailViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Applicant</h4>
    <hr />


    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Appointment)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Appointment)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.lastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.lastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.telephone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.telephone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.birthdate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.birthdate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.biography)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.biography)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.streetAddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.streetAddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.city)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.city)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.country)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.country)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.postalCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.postalCode)
            </dd>

          

     

        </dl>

    </div>
    <div class="col-md-6">

        @if (!string.IsNullOrEmpty(Model.photo))
            {
            <img src="@Url.Content(Model.photo)" align="center" style="height: 60%; width: 350px;display: block; margin-left: auto;
    margin-right: auto;" class="img-rounded" alt="Image" />
        }
    </div>
    
</div>
<table class="table">
    @if (Model.attachments.Count>0)
    {
        <tr>
            <th>Descripcion</th>
            <th>Link descarga</th>
        </tr>
    foreach (var item in Model.attachments)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.description)  
            </td>
            <td>
                <a href="@item.attachment">Download</a>
            </td>
         
        </tr>
    }
    }
</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idApplicant }) |
    @Html.ActionLink("Back to List", "Index")
</p>

testSancrisoft/Views/Applicants/Index.cshtml
@model IEnumerable<testSancrisoft.Models.Applicant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Appointment.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telephone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.birthdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.biography)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.streetAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.postalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Appointment.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.telephone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.birthdate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.biography)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.streetAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.postalCode)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.photo))
            {
                <img src="@Url.Content(item.photo)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            }
        </td>
        <td>
         
            @Html.ActionLink("Details", "Details", new { id=item.idApplicant })
        </td>
    </tr>
}

</table>


@*@section Scripts {


<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACJapLIVhm-uVWitwICh24232jYdkP1SQ&callback=initMap">
</script>
<script src="~/Scripts/apiGoogle.js"></script>

}*@

testSancrisoft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Applicant", "Create", "Applicants", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                 
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>